version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    networks:
      - expense_tracker_network
    volumes:
      - expense-tracker-volume:/data/db
  expense-tracker-api:
    container_name: expense-tracker-api
    image: expense-tracker-api:1.0
    depends_on:
      - mongo
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - expense_tracker_network
    environment:
      - DB_HOST=$MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

networks:
    expense_tracker_network:
        name: expense_tracker_network

volumes:
  expense-tracker-volume:
    name: "expense-tracker-mongovolume"
